<?php
header('Content-Type: application/json'); header('Cache-Control: no-store');
function fail($m){throw new Exception($m);}
function validQuestions($qs){if(!is_array($qs)||count($qs)<1||count($qs)>100) fail('Use 1–100 questions.');foreach($qs as &$q){if(!isset($q['text'],$q['options'],$q['correct'],$q['time'],$q['points'],$q['round'])||count($q['options'])!==4||!in_array($q['correct'],[0,1,2,3],true))fail('Every question needs four options and a correct answer.');$q['time']=max(5,min(120,(int)$q['time']));$q['points']=max(0,min(10000,(int)$q['points']));$q['round']=max(1,min(4,(int)$q['round']));}return $qs;}

function revealGame(&$s,$now){$q=$s['questions'][$s['index']];foreach($s['players'] as &$p){$a=$p['answers'][$s['index']]??null;$right=$a&&$a['choice']===$q['correct'];$points=0;if($right){$points=$q['round']===2?round(300+700*(1-min(1,$a['time']/$q['time']))):$q['points'];$p['streak']++;$points+=($p['streak']===3?100:($p['streak']===5?250:0));$p['correct']++;$p['best']=max($p['best'],$p['streak']);$p['times'][]=$a['time'];}else $p['streak']=0;$p['previousScore']=$p['score'];$p['score']+=$points;$p['result']=['right'=>(bool)$right,'points'=>$points,'choice'=>$a['choice']??null];}unset($p);$s['phase']='reveal';$s['phaseAt']=$now;}
function nextGame(&$s,$now){if($s['index']+1>=count($s['questions'])){$s['phase']='complete';}else{$previous=$s['questions'][$s['index']]['round'];$s['index']++;$s['phase']=$s['questions'][$s['index']]['round']!==$previous?'intro':'ready';}$s['phaseAt']=$now;}
function raceDuration($s){return max(8,min(60,ceil(count($s['players'])/8)*4));}
function tickGame(&$s,$now){if(!empty($s['paused']))return;$q=$s['questions'][$s['index']];$auto=$s['auto']??true;$count=0;foreach($s['players'] as $id=>$p){if(isset($p['answers'][$s['index']]))$count++;}
if($s['phase']==='active'&&($now>=$s['started']+$q['time']||($auto&&count($s['players'])>0&&$count===count($s['players'])))){if($auto)revealGame($s,$now);else $s['phase']='locked';}
elseif($auto&&$s['phase']==='locked')revealGame($s,$now);
elseif($auto&&$s['phase']==='reveal'&&$now>=($s['phaseAt']??$now)+5){$s['phase']='leaderboard';$s['phaseAt']=$now;}
elseif($auto&&$s['phase']==='leaderboard'&&$now>=($s['phaseAt']??$now)+raceDuration($s))nextGame($s,$now);
elseif($auto&&in_array($s['phase'],['intro','ready'])&&$now>=($s['phaseAt']??$now)+3){$s['phase']='active';$s['started']=$now;$s['phaseAt']=$now;}}

$f=null;
try{
$b=json_decode(file_get_contents('php://input'),true)??[];$op=$b['op']??'state';$code=$b['code']??'';
$dir=sys_get_temp_dir().'/class-clash-'.substr(hash('sha256',__DIR__),0,16);if(!is_dir($dir)&&!mkdir($dir,0700,true))fail('Cannot create game storage.');
if($op==='create'){$code=(string)random_int(100000,999999);$f=fopen($dir.'/'.$code.'.json','x+');if(!$f)fail('Try creating a room again.');flock($f,LOCK_EX);$s=['code'=>$code,'host'=>bin2hex(random_bytes(24)),'phase'=>'lobby','index'=>0,'started'=>0,'players'=>[],'questions'=>validQuestions($b['questions']??[]),'joining'=>true,'auto'=>true,'paused'=>false,'phaseAt'=>microtime(true)];$out=['code'=>$code,'token'=>$s['host']];}
else{if(!preg_match('/^\d{6}$/',$code))fail('Enter a six-digit room code.');$path=$dir.'/'.$code.'.json';if(!is_file($path))fail('Room not found.');$f=fopen($path,'r+');if(!$f||!flock($f,LOCK_EX))fail('Game storage unavailable.');$s=json_decode(stream_get_contents($f),true);if(!$s)fail('Room data unavailable.');$q=$s['questions'][$s['index']];$now=microtime(true);tickGame($s,$now);$host=isset($b['token'])&&hash_equals($s['host'],$b['token']);$pid=null;foreach($s['players'] as $id=>$p){if(isset($b['token'])&&hash_equals($p['token'],$b['token']))$pid=$id;}
if($op==='join'){if(!$s['joining']||$s['phase']!=='lobby')fail('Joining is closed.');if(count($s['players'])>=100)fail('Room is full.');$name=trim($b['name']??'');if(strlen($name)<1||strlen($name)>60)fail('Enter a name (up to 60 characters).');$id=bin2hex(random_bytes(8));$t=bin2hex(random_bytes(24));$s['players'][$id]=['name'=>$name,'token'=>$t,'score'=>0,'streak'=>0,'best'=>0,'correct'=>0,'times'=>[],'answers'=>[]];$out=['token'=>$t];}
elseif($op==='answer'){if(!$pid)fail('Join the room first.');if(!empty($s['paused'])||$s['phase']!=='active'||($b['index']??-1)!==$s['index'])fail('Answers are locked.');$a=$b['answer']??-1;if(!in_array($a,[0,1,2,3],true))fail('Invalid option.');if(isset($s['players'][$pid]['answers'][$s['index']]))fail('Your answer is already locked.');$s['players'][$pid]['answers'][$s['index']]=['choice'=>$a,'time'=>max(0,$now-$s['started'])];$out=['ok'=>true];}
elseif($op==='control'){if(!$host)fail('Only the host can control this room.');$action=$b['action']??'';$phase=$s['phase'];
if($action==='start'&&in_array($phase,['lobby','intro','ready'])){$s['phase']=($s['auto']??true)?'ready':'active';$s['started']=$now;$s['phaseAt']=$now;$s['joining']=false;}
elseif($action==='lock'&&$phase==='active')$s['phase']='locked';
elseif($action==='reveal'&&$phase==='locked'){revealGame($s,$now);}
elseif($action==='leaderboard'&&in_array($phase,['reveal','leaderboard'])){$s['phase']='leaderboard';$s['phaseAt']=$now;}
elseif($action==='next'&&in_array($phase,['reveal','leaderboard'])){nextGame($s,$now);}
elseif($action==='skip'&&in_array($phase,['ready','intro','active','locked'])){if($s['index']+1>=count($s['questions']))$s['phase']='complete';else{$s['index']++;$s['phase']='ready';}}
elseif($action==='pause'){if(empty($s['paused'])){$s['paused']=true;$s['pauseAt']=$now;}else{$delta=$now-$s['pauseAt'];$s['started']+=$delta;$s['phaseAt']=($s['phaseAt']??$now)+$delta;$s['paused']=false;}}
elseif($action==='mode'){$s['auto']=!($s['auto']??true);$s['phaseAt']=$now;}
elseif($action==='skin'){if(!isset($s['players'][$b['player']??'']))fail('Player not found.');$skin=$b['skin']??-1;if(!in_array($skin,[0,1,2,3],true))fail('Unknown character.');$s['players'][$b['player']]['skin']=$skin;}
elseif($action==='profile'){if(!isset($s['players'][$b['player']??'']))fail('Player not found.');$slot=$b['slot']??'head';if(!in_array($slot,['head','body']))fail('Invalid image type.');$data=$b['image']??'';if(strlen($data)>1500000)fail('Use an image smaller than 1 MB.');if(!preg_match('/^data:image\/(png|jpeg|webp|gif);base64,(.+)$/s',$data,$match))fail('Upload a PNG, JPEG, WebP or GIF.');$bytes=base64_decode($match[2],true);$info=$bytes!==false?@getimagesizefromstring($bytes):false;if(!$info||strlen($bytes)>1048576||$info[0]>4096||$info[1]>4096||!in_array($info['mime'],['image/png','image/jpeg','image/webp','image/gif']))fail('Use a valid image, up to 1 MB and 4096 pixels.');$file=$code.'-'.$b['player'].'-'.$slot.'.img';if(file_put_contents($dir.'/'.$file,$bytes)===false)fail('Could not store image.');$s['players'][$b['player']][$slot]='media.php?room='.$code.'&player='.$b['player'].'&slot='.$slot.'&v='.bin2hex(random_bytes(4));}
elseif($action==='end')$s['phase']='complete';
elseif($action==='restart'){$s['index']=0;$s['phase']='lobby';$s['joining']=true;$s['paused']=false;$s['phaseAt']=$now;foreach($s['players'] as &$p){$p['score']=0;$p['previousScore']=0;$p['streak']=0;$p['best']=0;$p['correct']=0;$p['times']=[];$p['answers']=[];unset($p['result']);}unset($p);}
elseif($action==='save'&&$phase==='lobby'){$s['questions']=validQuestions($b['questions']??[]);}
else fail('That control is unavailable in this phase.');$out=['ok'=>true];}
elseif($op==='state'){$q=$s['questions'][$s['index']];$revealed=in_array($s['phase'],['reveal','leaderboard','complete']);$safe=$q;if(!$revealed)unset($safe['correct'],$safe['explanation']);$board=[];$count=0;foreach($s['players'] as $id=>$p){if(isset($p['answers'][$s['index']]))$count++;$board[]=['id'=>$id,'skin'=>$p['skin']??null,'head'=>$p['head']??null,'body'=>$p['body']??null,'previousScore'=>$p['previousScore']??0,'name'=>$p['name'],'score'=>$p['score'],'correct'=>$p['correct'],'best'=>$p['best'],'average'=>count($p['times'])?array_sum($p['times'])/count($p['times']):null];}usort($board,function($a,$b){return $b['score']<=>$a['score']?:$b['correct']<=>$a['correct']?:strcmp($a['name'],$b['name']);});$clock=!empty($s['paused'])?($s['pauseAt']??$now):$now;$duration=$s['phase']==='reveal'?5:($s['phase']==='leaderboard'?raceDuration($s):3);$maxScore=350;foreach($s['questions'] as $item)$maxScore+=($item['round']===2?1000:$item['points']);$out=['auto'=>$s['auto']??true,'paused'=>$s['paused']??false,'phaseRemaining'=>max(0,ceil(($s['phaseAt']??$now)+$duration-$clock)),'maxScore'=>max(1,$maxScore),'code'=>$code,'phase'=>$s['phase'],'index'=>$s['index'],'total'=>count($s['questions']),'question'=>$safe,'remaining'=>max(0,ceil($s['started']+$q['time']-$clock)),'answered'=>$count,'players'=>$board];if($host)$out['questions']=$s['questions'];if($pid){$p=$s['players'][$pid];$out['me']=['name'=>$p['name'],'score'=>$p['score'],'streak'=>$p['streak'],'answer'=>$p['answers'][$s['index']]['choice']??null,'result'=>$revealed?($p['result']??null):null];}}
else fail('Unknown request.');}
rewind($f);$json=json_encode($s,JSON_UNESCAPED_UNICODE);if(fwrite($f,$json)===false)fail('Could not save the game.');ftruncate($f,strlen($json));fflush($f);flock($f,LOCK_UN);fclose($f);echo json_encode($out,JSON_UNESCAPED_UNICODE);
}catch(Throwable $e){if(is_resource($f)){flock($f,LOCK_UN);fclose($f);}http_response_code(400);echo json_encode(['error'=>$e->getMessage()]);}
